import { APIGatewayProxyResult } from 'aws-lambda';
import { withAuth, AuthenticatedEvent } from '../middleware/auth.js';

/**
 * Lambda: pages-attachments-download
 * GET /pages/{pageGuid}/attachments/{filename}
 *
 * Returns a temporary download URL for the attachment.
 * The URL is generated by the storage plugin (e.g., S3 pre-signed URL)
 * and the client fetches the binary directly from that URL.
 */
export const handler = withAuth(async (
  event: AuthenticatedEvent
): Promise<APIGatewayProxyResult> => {
  try {
    const pageGuid = event.pathParameters?.pageGuid || event.pathParameters?.guid;
    const rawFilename = event.pathParameters?.filename || event.pathParameters?.attachmentGuid;

    if (!pageGuid || !rawFilename) {
      return {
        statusCode: 400,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ error: 'Page GUID and filename are required' }),
      };
    }

    // API Gateway REST API does not URL-decode path parameters automatically
    const filename = decodeURIComponent(rawFilename);

    const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
    if (!UUID_REGEX.test(pageGuid)) {
      return {
        statusCode: 400,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ error: 'Invalid GUID format' }),
      };
    }

    const { getStoragePlugin } = await import('../storage/StoragePluginRegistry.js');
    const storagePlugin = getStoragePlugin();

    // Get metadata for content type
    let contentType = 'application/octet-stream';
    try {
      const metadata = await storagePlugin.getAttachmentMetadata(pageGuid, filename);
      contentType = metadata.contentType;
    } catch {
      // Fall back to generic type
    }

    // Generate a temporary download URL from the storage plugin
    const url = await storagePlugin.getAttachmentUrl(pageGuid, filename);

    return {
      statusCode: 200,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ url, contentType, filename }),
    };
  } catch (err: unknown) {
    console.error('Error downloading attachment:', err);
    const error = err as { code?: string; statusCode?: number; message?: string };

    if (error.code) {
      return {
        statusCode: error.statusCode || 500,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          error: error.message,
          code: error.code,
        }),
      };
    }

    return {
      statusCode: 500,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ error: 'Failed to download attachment' }),
    };
  }
});
