import type { Environment } from './environment.types';

// NOTE: This file is regenerated by `scripts/build-env.mjs` at production build time
// from NG_APP_* environment variables. Do not commit real values here.
export const environment: Environment = {
  production: true,
  apiBaseUrl: '',
  cognito: {
    region: '',
    userPoolId: '',
    clientId: '',
    domain: '',
    redirectUri: '',
  },
  disableAuth: false,
  aiAllowDestructive: true,
};
