#!/usr/bin/env node
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REQUIRED = [
  'NG_APP_API_BASE_URL',
  'NG_APP_COGNITO_REGION',
  'NG_APP_COGNITO_USER_POOL_ID',
  'NG_APP_COGNITO_CLIENT_ID',
  'NG_APP_COGNITO_DOMAIN',
  'NG_APP_COGNITO_REDIRECT_URI',
];

const missing = REQUIRED.filter((name) => !process.env[name]);
if (missing.length > 0) {
  console.error(`build-env: missing required env vars: ${missing.join(', ')}`);
  process.exit(1);
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, '../src/environments/environment.production.ts');

const env = {
  production: true,
  apiBaseUrl: process.env.NG_APP_API_BASE_URL,
  cognito: {
    region: process.env.NG_APP_COGNITO_REGION,
    userPoolId: process.env.NG_APP_COGNITO_USER_POOL_ID,
    clientId: process.env.NG_APP_COGNITO_CLIENT_ID,
    domain: process.env.NG_APP_COGNITO_DOMAIN,
    redirectUri: process.env.NG_APP_COGNITO_REDIRECT_URI,
  },
  disableAuth: false,
  aiAllowDestructive: process.env.NG_APP_AI_ALLOW_DESTRUCTIVE !== 'false',
};

const banner = '// Generated by scripts/build-env.mjs -- do not edit by hand.';
const body = `import type { Environment } from './environment.types';\n\nexport const environment: Environment = ${JSON.stringify(env, null, 2)};\n`;

writeFileSync(outPath, `${banner}\n\n${body}`, 'utf8');
console.log(`build-env: wrote ${outPath}`);
