// Generated by scripts/build-env.mjs -- do not edit by hand.

import type { Environment } from './environment.types';

export const environment: Environment = {
  "production": true,
  "apiBaseUrl": "https://api.wiki.bluefin605.com",
  "cognito": {
    "region": "ap-southeast-2",
    "userPoolId": "ap-southeast-2_NY9kyg83p",
    "clientId": "672dnm6p6c5svbe88i5835vnvt",
    "domain": "auth.wiki.bluefin605.com",
    "redirectUri": "https://wiki.bluefin605.com/callback"
  },
  "disableAuth": false,
  "aiAllowDestructive": true
};
